### ISSUE TITLE
Improve http requests

### ISSUE THREAD

**Issue by mungujn** [louismomo66/scraper_go#3]
To allow easy testing of http requests using mocks, check out techniques described here 

- https://www.thegreatcodeadventure.com/mocking-http-requests-in-golang/
- https://medium.com/zus-health/mocking-outbound-http-requests-in-go-youre-probably-doing-it-wrong-60373a38d2aa

**Comment by louismomo66** [comment]
used mock tests

**Comment by louismomo66** [comment]
I was able to do mock testing
